import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml",
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0xc8d3f5"
yellow = "0xffc777"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0x828bb8"
yellow = "0xffc777"

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"


[font]
size = 18.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"

[window.padding]
x = 10
y = 10

